# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wazuh ESLint

on:
  pull_request:
    branches:
      'main'
      # - '*.*-*.*'
      # - '*.*-*.*-wzd'

jobs:
  setup-wazuh-app:
    name: Run setup environment wazuh app
    runs-on: ubuntu-latest
    steps:
      - name: Step 01 - Download Project wazuh-app
        uses: actions/checkout@v2
        with:
          path: /home/runner/work/pruebaprecommit/pruebaprecommit
      - name: Step 02 - Install dependencies of wazuh
        run: |
          cd wazuh
          yarn install
      - name: Step 03 - Run ESLint
        run: |
          cd /home/runner/work/pruebaprecommit/pruebaprecommit
          yarn run lint
